# Generated by Django 5.0.6 on 2024-07-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personality_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
